"""
Django settings for IATI Dashboard project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.crypto import get_random_string

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

chars = "abcdefghijklmnopqrstuvwxyz0123456789!@#%^&*(-_=+)"
secret_key = get_random_string(50, chars)

env = environ.Env(  # set default values and casting
    DEBUG=(bool, False),
    SECRET_KEY=(str, secret_key),
    SENTRY_DSN=(str, None),
    USE_X_FORWARDED_HOST=(bool, False),
    ALLOWED_HOSTS=(list, [".dashboard.iatistandard.org", "localhost", "127.0.0.1"]),
    # Allow api features to only be enabled on a dev instance for now
    # This means we can keep it off live until we assess the performance implications
    ENABLE_API_ALPHA=(bool, False),
    ENABLE_FILTERS_ALPHA=(bool, False),
    REALTIME_UPDATE_SERVICE_LOOP_SLEEP=(int, 3),
    REALTIME_UPDATE_SERVICE_LOOP_SLEEP_AFTER_ERROR=(int, 15),
    AZ_SERVICE_BUS_CONNECTION_STRING=(str, None),
    AZ_SERVICE_BUS_REGISTRY_CHANGES_TOPIC_NAME=(str, None),
    AZ_SERVICE_BUS_REGISTRY_CHANGES_SUBSCRIPTION_NAME=(str, None),
    AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_TOPIC_NAME=(str, None),
    AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_SUBSCRIPTION_NAME=(str, None),
)


SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

SENTRY_DSN = env("SENTRY_DSN")

USE_X_FORWARDED_HOST = env("USE_X_FORWARDED_HOST")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

ENABLE_API_ALPHA = env("ENABLE_API_ALPHA")
ENABLE_FILTERS_ALPHA = env("ENABLE_FILTERS_ALPHA")


if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.logging import ignore_logger

    ignore_logger("django.security.DisallowedHost")

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=0,
    )

# Application definition

INSTALLED_APPS = [
    "iati_dashboard",
    "iati_dashboard.ui",
    "iati_dashboard.api",
    "django.contrib.staticfiles",
    "django_extensions",
    "rest_framework",
    "django_filters",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "drf_spectacular",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Dashboard API",
    "DESCRIPTION": "The new api for the dashboard website, designed as the main point of access to metadata.",
    "VERSION": "0.9.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "iati_dashboard.ui.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
            "environment": "iati_dashboard.ui.jinja2.environment",
        },
    },
]

WSGI_APPLICATION = "iati_dashboard.ui.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": env.db()}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "iati_dashboard" / "static",
]
STATIC_ROOT = "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#
# Relative (to dashboard/) paths to IATI data and output directories.
#
DASHBOARD_STATS_DIRECTORY = "stats-calculated"
DASHBOARD_DATA_DIRECTORY = "data"
DASHBOARD_BASE_DIRECTORY = "."
DASHBOARD_OUT_DIRECTORY = "out"

DASHBOARD_CREATE_CACHE_FILES = False

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


REALTIME_UPDATE_PROCESSOR = {
    "REALTIME_UPDATE_SERVICE_LOOP_SLEEP": env("REALTIME_UPDATE_SERVICE_LOOP_SLEEP"),
    "REALTIME_UPDATE_SERVICE_LOOP_SLEEP_AFTER_ERROR": env("REALTIME_UPDATE_SERVICE_LOOP_SLEEP_AFTER_ERROR"),
    "AZ_SERVICE_BUS_CONNECTION_STRING": env("AZ_SERVICE_BUS_CONNECTION_STRING"),
    "AZ_SERVICE_BUS_REGISTRY_CHANGES_TOPIC_NAME": env("AZ_SERVICE_BUS_REGISTRY_CHANGES_TOPIC_NAME"),
    "AZ_SERVICE_BUS_REGISTRY_CHANGES_SUBSCRIPTION_NAME": env("AZ_SERVICE_BUS_REGISTRY_CHANGES_SUBSCRIPTION_NAME"),
    "AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_TOPIC_NAME": env("AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_TOPIC_NAME"),
    "AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_SUBSCRIPTION_NAME": env(
        "AZ_SERVICE_BUS_DATASET_CHECK_RESULTS_SUBSCRIPTION_NAME"
    ),
}
