"""Text fragments for page titles, navigation and page leaders/sub-leaders"""

import copy

top_titles = {
    "index": "Home",
    "publishers": "Reporting Orgs",
    "errors": "Errors",
    "publishing_stats": "Publishing Statistics",
    "exploring_data": "Exploring Data",
    "faq": "FAQ",
}

page_titles = {
    "index": "Dashboard Home",
    "headlines": "Headlines",
    "errors": "Errors",
    "exploring_data": "Exploring Data",
    "faq": "Frequently Asked Questions",
    "publishers": "IATI Reporting Orgs",
    "files": "IATI Files",
    "activities": "IATI Activities",
    "download": "Download Errors",
    "xml": "XML Errors",
    "validation": "Validation Against the Schema",
    "versions": "Versions",
    "rulesets": "Rulesets",
    "licenses": "Licenses listed on the Registry",
    "organisation": "Organisation XML Files",
    "identifiers": "Duplicate Activity Identifiers",
    "registration_agencies": "Registration Agencies",
    "reporting_orgs": "Reporting Org Identifier Inconsistencies",
    "elements": "Elements",
    "codelists": "Codelists",
    "booleans": "Booleans",
    "dates": "Dates",
    "traceability": "Traceability",
    "org_ids": "Organisation Identifiers",
    "publishing_stats": "Publishing Statistics",
    "timeliness_timelag": "Timeliness Timelag",
    "timeliness_frequency": "Timeliness Frequency",
    "forwardlooking": "Forward Looking",
    "comprehensiveness_summary": "Comprehensiveness Summary",
    "comprehensiveness_core": "Comprehensiveness Core",
    "comprehensiveness_financials": "Comprehensiveness Financials",
    "comprehensiveness_valueadded": "Comprehensiveness Value-Added",
    "summary_stats": "Summary Statistics",
    "humanitarian": "Humanitarian Reporting",
    "ati_publishers": "",
    "ati_publisher_detail": "",
}

page_leads = {
    "index": "Statistics, charts and metrics on data accessed via the IATI Registry.",
    "Errors": "What needs fixing in IATI data?",
    "exploring_data": "Which parts of the IATI Standard are being used?",
    "headlines": "What is the size, scope and scale of published IATI data?",
    "publishers": "How many organisations are publishing IATI data?",
    "files": "How many IATI files are published?",
    "activities": "How many IATI activities are published?",
    "download": "How many files failed to download?",
    "xml": "Which files have XML errors?",
    "validation": "Which files fail schema validation?",
    "versions": 'Which <a href="https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/versions/">versions of the IATI Standard</a> are being used?',
    "rulesets": "How does IATI data test against rulesets?",
    "licenses": "Which licences are used by IATI reporting orgs?",
    "organisation": "Who is publishing IATI Organisation files?",
    "identifiers": "Where are there duplicate IATI identifiers?",
    "reporting_orgs": "Where are reporting organisation identifiers inconsistent with the IATI Registry?",
    "elements": "How are the IATI Standard elements used by reporting orgs?",
    "codelists": "How are codelists used in IATI data?",
    "booleans": "How are booleans used in IATI data?",
    "dates": "What date ranges do reporting orgs publish data for?",
    "traceability": "How much of a reporting org’s spending is traceable to other reporting orgs’ activities?",
    "org_ids": "Are organisation identifiers being used correctly?",
}
page_sub_leads = {
    "publishers": "Reporting Orgs represent organisation accounts in the IATI Registry.",
    "files": "Files are logged on the IATI Registry by reporting orgs. The files contain data on activities and the organisation.  A reportinrg org may have multiple files, which can contain multiple activities.",
    "activities": "Activities are the individual projects found in files.  A file can contain one or many activities, from a reporting org.",
    "download": "Files that failed to download, when accessed via the IATI Registry. Note: This may because no URL is listed on the registry, or when requesting the URL the reporting org's server returns an error message (e.g. because there is no file at that location). Some files that failed to download when last checked may since have become available.",
    "xml": "This page shows files that are not well-formed XML, accessed via the IATI Registry.",
    "validation": 'IATI files are validated against the appropriate <a href="https://iatistandard.org/schema/">IATI Schema</a>. Note: this is based on the version declared in the file and whether it\'s an activity/organisation file.',
    "versions": "Files are reported against a specific version of the IATI Standard, using the <code class='iati-code'>version</code> attribute in the <code class='iati-code'>iati-activities</code> element.",
    "rulesets": "The IATI Ruleset describe constraints, conditions and logics that are additional to the IATI schema. Note: Currently, on the IATI Standard Ruleset is tested.",
    "licenses": "Licences are applied to files by reporting orgs on the IATI Registry, and explain how data can be used.",
    "organisation": "Checking the IATI Registry for files that have <code class='iati-code'>iati-organisations</code> as the root element. IATI Organisation files contain general information about the organisations in the delivery chain.",
    "identifiers": "Checking the <code class='iati-code'>iati-identifier</code> element for duplicate values per reporting org. A duplicate appears if a reporting org creates two activities with the same identifier.",
    "reporting_orgs": "Checking the <code class='iati-code'>reporting-org</code> identifiers in IATI data.",
    "elements": "Checking usage of all elements/attributes within the IATI Standard.",
    "codelists": "Checking usage of codelists across IATI data files.",
    "booleans": "Checking usage of booleans across IATI data files. Booleans are values that are either true or false. In XML <code class='iati-code'>true</code> or <code class='iati-code'>1</code> can be used for true and <code class='iati-code'>false</code> or <code class='iati-code'>0</code> can be used for false.",
}

short_page_titles = copy.copy(page_titles)
short_page_titles.update(
    {
        "publishers": "Reporting Orgs",
        "files": "Files",
        "activities": "Activities",
        "validation": "Schema Validation",
        "licenses": "Licenses",
        "organisation": "Organisation XML",
        "identifiers": "Duplicate Identifiers",
    }
)

top_navigation = ["publishers", "errors", "exploring_data", "publishing_stats", "faq"]
navigation = {
    "errors": [
        "download",
        "xml",
        "validation",
        "identifiers",
        "reporting_orgs",
    ],
    "exploring_data": [
        "publishers",
        "files",
        "activities",
        "elements",
        "codelists",
        "booleans",
        "dates",
        "versions",
        "licenses",
        "organisation",
        "traceability",
        "org_ids",
    ],
    "publishing_stats": [
        "timeliness_frequency",
        "timeliness_timelag",
        "forwardlooking",
        "comprehensiveness_summary",
        "comprehensiveness_core",
        "comprehensiveness_financials",
        "comprehensiveness_valueadded",
        "summary_stats",
        "humanitarian",
    ],
}

LICENSE_NAMES = {
    "notspecified": "Other::License Not Specified",
    "odc-pddl": "OKD Compliant::Open Data Commons Public Domain Dedication and Licence (PDDL)",
    "odc-odbl": "OKD Compliant::Open Data Commons Open Database License (ODbL)",
    "odc-by": "OKD Compliant::Open Data Commons Attribution Licence",
    "cc-zero": "OKD Compliant::Creative Commons CCZero",
    "cc-by": "OKD Compliant::Creative Commons Attribution",
    "cc-by-sa": "OKD Compliant::Creative Commons Attribution Share-Alike",
    "gfdl": "OKD Compliant::GNU Free Documentation License",
    "ukclickusepsi": "OKD Compliant::UK Click Use PSI",
    "other-open": "OKD Compliant::Other (Open)",
    "other-pd": "OKD Compliant::Other (Public Domain)",
    "other-at": "OKD Compliant::Other (Attribution)",
    "ukcrown-withrights": "OKD Compliant::UK Crown Copyright with data.gov.uk rights",
    "hesa-withrights": "OKD Compliant::Higher Education Statistics Agency Copyright with data.gov.uk rights",
    "localauth-withrights": "OKD Compliant::Local Authority Copyright with data.gov.uk rights",
    "uk-ogl": "OKD Compliant::UK Open Government Licence (OGL)",
    "met-office-cp": "Non-OKD Compliant::Met Office UK Climate Projections Licence Agreement",
    "cc-nc": "Non-OKD Compliant::Creative Commons Non-Commercial (Any)",
    "ukcrown": "Non-OKD Compliant::UK Crown Copyright",
    "other-nc": "Non-OKD Compliant::Other (Non-Commercial)",
    "other-closed": "Non-OKD Compliant::Other (Not Open)",
    "bsd-license": "OSI Approved::New and Simplified BSD licenses",
    "gpl-2.0": "OSI Approved::GNU General Public License (GPL)",
    "gpl-3.0": "OSI Approved::GNU General Public License version 3.0 (GPLv3)",
    "lgpl-2.1": 'OSI Approved::GNU Library or "Lesser" General Public License (LGPL)',
    "mit-license": "OSI Approved::MIT license",
    "afl-3.0": "OSI Approved::Academic Free License 3.0 (AFL 3.0)",
    "apl1.0": "OSI Approved::Adaptive Public License",
    "apache": "OSI Approved::Apache Software License",
    "apache2.0": "OSI Approved::Apache License, 2.0",
    "apsl-2.0": "OSI Approved::Apple Public Source License",
    "artistic-license-2.0": "OSI Approved::Artistic license 2.0",
    "attribution": "OSI Approved::Attribution Assurance Licenses",
    "ca-tosl1.1": "OSI Approved::Computer Associates Trusted Open Source License 1.1",
    "cddl1": "OSI Approved::Common Development and Distribution License",
    "cpal_1.0": "OSI Approved::Common Public Attribution License 1.0 (CPAL)",
    "cuaoffice": "OSI Approved::CUA Office Public License Version 1.0",
    "eudatagrid": "OSI Approved::EU DataGrid Software License",
    "eclipse-1.0": "OSI Approved::Eclipse Public License",
    "ecl2": "OSI Approved::Educational Community License, Version 2.0",
    "eiffel": "OSI Approved::Eiffel Forum License",
    "ver2_eiffel": "OSI Approved::Eiffel Forum License V2.0",
    "entessa": "OSI Approved::Entessa Public License",
    "fair": "OSI Approved::Fair License",
    "frameworx": "OSI Approved::Frameworx License",
    "ibmpl": "OSI Approved::IBM Public License",
    "intel-osl": "OSI Approved::Intel Open Source License",
    "jabber-osl": "OSI Approved::Jabber Open Source License",
    "lucent-plan9": "OSI Approved::Lucent Public License (Plan9)",
    "lucent1.02": "OSI Approved::Lucent Public License Version 1.02",
    "mitre": "OSI Approved::MITRE Collaborative Virtual Workspace License (CVW License)",
    "motosoto": "OSI Approved::Motosoto License",
    "mozilla": "OSI Approved::Mozilla Public License 1.0 (MPL)",
    "mozilla1.1": "OSI Approved::Mozilla Public License 1.1 (MPL)",
    "nasa1.3": "OSI Approved::NASA Open Source Agreement 1.3",
    "naumen": "OSI Approved::Naumen Public License",
    "nethack": "OSI Approved::Nethack General Public License",
    "nokia": "OSI Approved::Nokia Open Source License",
    "oclc2": "OSI Approved::OCLC Research Public License 2.0",
    "opengroup": "OSI Approved::Open Group Test Suite License",
    "osl-3.0": "OSI Approved::Open Software License 3.0 (OSL 3.0)",
    "php": "OSI Approved::PHP License",
    "pythonpl": "OSI Approved::Python license",
    "PythonSoftFoundation": "OSI Approved::Python Software Foundation License",
    "qtpl": "OSI Approved::Qt Public License (QPL)",
    "real": "OSI Approved::RealNetworks Public Source License V1.0",
    "rpl1.5": "OSI Approved::Reciprocal Public License 1.5 (RPL1.5)",
    "ricohpl": "OSI Approved::Ricoh Source Code Public License",
    "sleepycat": "OSI Approved::Sleepycat License",
    "sun-issl": "OSI Approved::Sun Industry Standards Source License (SISSL)",
    "sunpublic": "OSI Approved::Sun Public License",
    "sybase": "OSI Approved::Sybase Open Watcom Public License 1.0",
    "UoI-NCSA": "OSI Approved::University of Illinois/NCSA Open Source License",
    "vovidapl": "OSI Approved::Vovida Software License v. 1.0",
    "W3C": "OSI Approved::W3C License",
    "wxwindows": "OSI Approved::wxWindows Library License",
    "xnet": "OSI Approved::X.Net License",
    "zpl": "OSI Approved::Zope Public License",
    "zlib-license": "OSI Approved::zlib/libpng license",
}
