# Generated by Django 5.1.5 on 2025-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("short_name", models.CharField()),
                ("human_readable_name", models.CharField()),
                ("stats_json", models.JSONField()),
                (
                    "traceable_sum_commitments_and_disbursements_by_publisher_id_den",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F(
                            "stats_json__traceable_sum_commitments_and_disbursements_by_publisher_id_denominator"
                        ),
                        output_field=models.JSONField(),
                    ),
                ),
                (
                    "activities",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("stats_json__activities"), output_field=models.JSONField()
                    ),
                ),
                (
                    "traceable_activities_by_publisher_id",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("stats_json__traceable_activities_by_publisher_id"),
                        output_field=models.JSONField(),
                    ),
                ),
                (
                    "traceable_activities_by_publisher_id_denominator",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("stats_json__traceable_activities_by_publisher_id_denominator"),
                        output_field=models.JSONField(),
                    ),
                ),
                (
                    "traceable_sum_commitments_and_disbursements_by_publisher_id",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("stats_json__traceable_sum_commitments_and_disbursements_by_publisher_id"),
                        output_field=models.JSONField(),
                    ),
                ),
            ],
        ),
    ]
