# Generated by Django 5.1.4 on 2025-01-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="comprehensiveness",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publisher",
            name="forwardlooking",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publisher",
            name="has_future_transactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="publisher",
            name="humanitarian",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publisher",
            name="summary_stats",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publisher",
            name="timeliness_frequency",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="stats_json",
            field=models.JSONField(default=dict),
        ),
    ]
