# Generated by Django 5.1.5 on 2025-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0002_publisher_comprehensiveness_publisher_forwardlooking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="activity_files",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__activity_files"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="file_size",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__file_size"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="hierarchies",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__hierarchies"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="organisation_files",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__organisation_files"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="organisations",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__organisations"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="reporting_orgs",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__reporting_orgs"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="timelag",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__timelag"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="transaction_months_with_year",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.F("stats_json__transaction_months_with_year"),
                output_field=models.JSONField(),
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="validation_datasets",
            field=models.JSONField(default=dict),
        ),
    ]
