# Generated by Django 5.1.6 on 2025-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0003_publisher_activity_files_publisher_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="elements",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__elements"), output_field=models.JSONField()
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="elements_total",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("stats_json__elements_total"), output_field=models.JSONField()
            ),
        ),
    ]
