# Generated by Django 5.2.1 on 2025-05-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0006_alter_dataset_short_name_alter_publisher_short_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Publisher",
            new_name="ReportingOrg",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="publisher",
            new_name="reporting_org",
        ),
    ]
