# Generated by Django 5.2.3 on 2025-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0007_rename_publisher_reportingorg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingorg",
            name="recipient_country_code",
            field=models.JSONField(default=list),
        ),
    ]
