# Generated by Django 5.2.3 on 2025-07-03 12:51

import uuid

from django.db import migrations, models


def populate_uuids(apps, schema_editor):
    ReportingOrg = apps.get_model("iati_dashboard", "ReportingOrg")
    for row in ReportingOrg.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    Dataset = apps.get_model("iati_dashboard", "Dataset")
    for row in Dataset.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0008_reportingorg_recipient_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="reportingorg",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dataset",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="reportingorg",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
