# Generated by Django 5.2.3 on 2025-07-03 13:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0010_add_temp_dataset_pseudo_fk_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataset",
            name="id",
        ),
        migrations.RemoveField(
            model_name="reportingorg",
            name="id",
        ),
        migrations.AlterField(
            model_name="dataset",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reportingorg",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
