# Generated by Django 5.2.3 on 2025-07-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0011_make_uuid_fields_primary_keys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataset",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="reportingorg",
            old_name="uuid",
            new_name="id",
        ),
    ]
