# Generated by Django 5.2.3 on 2025-08-20 19:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0013_dataset_reporting_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("dataset_id", models.UUIDField(db_index=True)),
                ("reporting_org_id", models.UUIDField(db_index=True)),
                ("initiating_user_id", models.UUIDField(null=True)),
                ("initiating_user_name", models.CharField(null=True)),
                ("initiating_application_id", models.UUIDField(null=True)),
                ("initiating_application_name", models.CharField(null=True)),
                ("initiating_organisation_id", models.UUIDField(null=True)),
                ("initiating_organisation_name", models.UUIDField(null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REGISTRY_DATASET_RECORD_CREATED", "Dataset record created on the IATI Registry"),
                            ("REGISTRY_DATASET_RECORD_UPDATED", "Dataset record updated on the IATI Registry"),
                            ("REGISTRY_DATASET_RECORD_DELETED", "Dataset record deleted on the IATI Registry"),
                            ("DOWNLOAD_STATUS_CHANGED", "Dataset download status changed"),
                            ("DATASET_CONTENT_CHANGED", "Dataset content changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message_payload", models.CharField()),
                ("data_fields_current", models.JSONField()),
                ("data_fields_previous", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportingOrgEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("reporting_org_id", models.UUIDField(db_index=True)),
                ("initiating_user_id", models.UUIDField(null=True)),
                ("initiating_user_name", models.CharField(null=True)),
                ("initiating_application_id", models.UUIDField(null=True)),
                ("initiating_application_name", models.CharField(null=True)),
                ("initiating_organisation_id", models.UUIDField(null=True)),
                ("initiating_organisation_name", models.UUIDField(null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "REGISTRY_REPORTING_ORG_RECORD_CREATED",
                                "Reporting Org record created on the IATI Registry",
                            ),
                            (
                                "REGISTRY_REPORTING_ORG_RECORD_UPDATED",
                                "Reporting Org record updated on the IATI Registry",
                            ),
                            (
                                "REGISTRY_REPORTING_ORG_RECORD_DELETED",
                                "Reporting Org record deleted on the IATI Registry",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("message_payload", models.CharField()),
                ("data_fields_current", models.JSONField()),
                ("data_fields_previous", models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="most_recent_dataset_check_result",
            field=models.JSONField(default=dict),
        ),
    ]
