# Generated by Django 5.2.6 on 2025-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0015_dataset_metadata_json_reportingorg_metadata_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingorg",
            name="file_types",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="reportingorg",
            name="hq_country",
            field=models.GeneratedField(
                db_persist=True, expression=models.F("metadata_json__hq_country"), output_field=models.JSONField()
            ),
        ),
    ]
