# Generated by Django 5.2.11 on 2026-06-04 10:16

import uuid

from django.db import migrations, models

import iati_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0017_dataset_licence_id_reportingorg_created_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetHistoricEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message_type", models.CharField(db_index=True)),
                ("display_category", models.CharField(db_index=True)),
                ("message_date", models.DateTimeField(db_index=True)),
                ("dataset_id", models.UUIDField(db_index=True)),
                ("payload", iati_dashboard.models.JSONTextField()),
            ],
            options={
                "db_table": "dataset_activity_stream",
                "managed": False,
            },
        ),
    ]
