# Generated by Django 5.2.14 on 2026-06-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0019_dataset_activities_dataset_file_size_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatasetEvent",
        ),
    ]
