# Generated by Django 5.2.15 on 2026-07-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iati_dashboard", "0021_dataset_check_result_json_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatasetEvent",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="most_recent_dataset_check_result",
        ),
    ]
