name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database_name
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Lint - flake8
      run: flake8
    - name: Lint - black
      run: black . --check
    - name: Lint - isort
      run: isort . --check-only
    - name: Fetch data
      run: ./fetch_data.sh no-download-errors-history
    - name: Fetch stats
      run: |
        mkdir out
        ./partial_stats_for_unit_tests.sh
    - name: Set up django
      env:
        # The DB in ACTIVITY_STREAM_DATABASE_URL doesn't exist, but needs somethign to avoid
        # warnings from the Django environment variable parser
        ACTIVITY_STREAM_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/activity_stream"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_database_name"
      run: |
        python manage.py collectstatic
        python manage.py migrate
        python manage.py dashboard_import
        mkdir iati_dashboard/fixtures/
        python manage.py dumpdata iati_dashboard.ReportingOrg > iati_dashboard/fixtures/reporting_orgs.json
        python manage.py dumpdata iati_dashboard.Dataset > iati_dashboard/fixtures/datasets.json
    - name: Set up W3C HTML validator
      run: |
        docker run -d -p 8888:8888 ghcr.io/validator/validator:latest
    - name: Run tests
      env:
        ACTIVITY_STREAM_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/activity_stream"
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_database_name"
        DASHBOARD_ROOT_URL: "http://localhost:8000"
        ENABLE_API_ALPHA: "True"
      run: |
        python manage.py runserver & sleep 5
        pytest iati_dashboard
    # - name: Coveralls
    #   run: coveralls --service=github-actions
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
